### ISSUE TITLE
In cpp version, auto is better than int

### ISSUE THREAD

**Issue by ZhangBob123** [ytmo/LeapYearCheak#1]
in c++ 11, auto is useful.
Foe example:
for ( auto i=0;  i<100;  i++)
{
    cout<<"auto is useful"<<endl;
}

**Comment by TomsProject** [comment]
BUT now I needn't C++11's new characteristic.
And why I should use auto nor int? auto has to do type derivation, and the result still IS int.

**Comment by TomsProject** [comment]
I just make a c++ version with auto of LeapYearCheak, thanks for your GOOD FIRST ISSUE
